require('after.plugins.devicons')
require('after.plugins.fugitive')
require('after.plugins.harpoon')
require('after.plugins.lsp')
require('after.plugins.telescope')
require('after.plugins.tree')
require('after.plugins.treesitter')
require('after.plugins.undotree')
