local builtin = require('telescope.builtin')

vim.keymap.set('n', '<leader>F', builtin.live_grep)
vim.keymap.set('n', '<leader>d', builtin.diagnostics)
vim.keymap.set('n', '<leader>f', builtin.find_files)
vim.keymap.set('n', '<leader>g', builtin.grep_string)
vim.keymap.set('n', '<leader>j', builtin.jumplist)
vim.keymap.set('n', '<leader>l', builtin.loclist)
vim.keymap.set('n', '<leader>q', builtin.quickfix)
vim.keymap.set('n', '<leader>s', builtin.lsp_document_symbols)
vim.keymap.set('n', 'gr', builtin.lsp_references)
