require('nvim-treesitter.configs').setup {
    ensure_installed = {
        'c_sharp',
        'cpp',
        'css',
        'dockerfile',
        'html',
        'javascript',
        'json',
        'json5',
        'jsonc',
        'lua',
        'markdown',
        'php',
        'python',
        'regex',
        'rust',
        'scss',
        'sql',
        'toml',
        'tsx',
        'typescript',
        'vue',
        'yaml'
    },
    sync_install = false,
    auto_install = true,
    highlight = {
        enable = true,
        additional_vim_regex_highlighting = false,
    },
}
